openapi: "3.0.0"
info: 
  version: 1.0.0 
  title: logging-api
servers:
  - url: /v1
paths:
  /var/log/{file-name}: 
    get: 
      summary: "Retrieve recent log entries"
      operationId: "tail"
      parameters:
        - name: file-name
          in: path
          description: The file to be logged in /var/log/
          required: true
          schema:
            type: string
        - name: term 
          in: query
          description: The term to be searched in the log file - this is not case sensitive 
          required: true
          schema: 
            type: string
        - name: number-of-entries 
          description: The number of entries to be returned 
          in: query
          required: true
          schema:
            type: number
      responses:
        default: 
          description: The lookup was not successful 
          content:
            application/json: 
              schema: 
                type: object
                required:
                  - "message"
                  - "code"
                properties:
                  message: 
                    type: string
                    example: 'NOT FOUND'
                  code: 
                    type: number
                    example: '404'
                  cause: 
                    type: string
                    example: 'Log file does not exist'
        200: 
          description: The lookup was successful
          content:
            application/json:
              schema: 
                type: object
                required:
                  - "message"
                  - "code"
                  - "data"
                properties:
                  message: 
                    type: string
                    example: 'OK'
                  code: 
                    type: number
                    example: '200'
                  data: 
                    type: array
                    items: 
                      type: string

